import 'package:flutter/material.dart';

/// Defines Pakistani worker categories, cities, payment methods, and seed profiles.
class PakistanConstants {
  // ── Worker Categories ──────────────────────────────────────────────────
  static const List<Map<String, dynamic>> categories = [
    {
      'id': 'electrician',
      'name': 'Electrician',
      'urdu': 'بجلی والا',
      'icon': Icons.electrical_services,
      'avgRatePkr': 800,
    },
    {
      'id': 'plumber',
      'name': 'Plumber',
      'urdu': 'نلکے والا',
      'icon': Icons.plumbing,
      'avgRatePkr': 700,
    },
    {
      'id': 'ac_technician',
      'name': 'AC Technician',
      'urdu': 'اے سی ٹیکنیشن',
      'icon': Icons.ac_unit,
      'avgRatePkr': 1500,
    },
    {
      'id': 'solar_installer',
      'name': 'Solar Installer',
      'urdu': 'سولر انسٹالر',
      'icon': Icons.solar_power,
      'avgRatePkr': 2500,
    },
    {
      'id': 'generator_ups',
      'name': 'UPS & Generator',
      'urdu': 'یو پی ایس اور جنریٹر',
      'icon': Icons.power,
      'avgRatePkr': 1200,
    },
    {
      'id': 'mechanic',
      'name': 'Mechanic',
      'urdu': 'مستری',
      'icon': Icons.car_repair,
      'avgRatePkr': 1000,
    },
    {
      'id': 'painter',
      'name': 'Painter',
      'urdu': 'پینٹر',
      'icon': Icons.format_paint,
      'avgRatePkr': 900,
    },
    {
      'id': 'carpenter',
      'name': 'Carpenter',
      'urdu': 'بڑھئی',
      'icon': Icons.handyman,
      'avgRatePkr': 1100,
    },
    {
      'id': 'tutor',
      'name': 'Home Tutor',
      'urdu': 'ٹیوٹر',
      'icon': Icons.menu_book,
      'avgRatePkr': 1500,
    },
    {
      'id': 'driver',
      'name': 'Driver',
      'urdu': 'ڈرائیور',
      'icon': Icons.directions_car,
      'avgRatePkr': 800,
    },
    {
      'id': 'cleaner',
      'name': 'House Cleaner',
      'urdu': 'صفائی والا',
      'icon': Icons.cleaning_services,
      'avgRatePkr': 600,
    },
    {
      'id': 'mason',
      'name': 'Mason / Builder',
      'urdu': 'راج مستری',
      'icon': Icons.construction,
      'avgRatePkr': 1300,
    },
  ];

  // ── Pakistani Cities & Coordinates ─────────────────────────────────────
  static const List<Map<String, dynamic>> cities = [
    {'name': 'All Cities', 'lat': 33.6844, 'lng': 73.0479},
    {'name': 'Islamabad', 'lat': 33.6844, 'lng': 73.0479},
    {'name': 'Lahore', 'lat': 31.5204, 'lng': 74.3587},
    {'name': 'Karachi', 'lat': 24.8607, 'lng': 67.0011},
    {'name': 'Rawalpindi', 'lat': 33.5973, 'lng': 73.0479},
    {'name': 'Faisalabad', 'lat': 31.4504, 'lng': 73.1350},
    {'name': 'Multan', 'lat': 30.1798, 'lng': 71.4782},
    {'name': 'Peshawar', 'lat': 34.0151, 'lng': 71.5249},
  ];

  static List<String> get majorCities => cities
      .where((c) => c['name'] != 'All Cities')
      .map((c) => c['name'] as String)
      .toList();

  // ── Payment Methods ────────────────────────────────────────────────────
  static const List<Map<String, dynamic>> paymentMethods = [
    {
      'id': 'jazzcash',
      'name': 'JazzCash Mobile Account',
      'shortName': 'JazzCash',
      'icon': Icons.phone_android,
      'color': 0xFFE2001A,
      'requiresPhone': true,
      'accountHint': '+92 300 1234567',
    },
    {
      'id': 'easypaisa',
      'name': 'EasyPaisa Wallet',
      'shortName': 'EasyPaisa',
      'icon': Icons.account_balance_wallet,
      'color': 0xFF00A950,
      'requiresPhone': true,
      'accountHint': '+92 345 1234567',
    },
    {
      'id': 'raast_qr',
      'name': 'Raast / IBFT Instant QR • راست آئی بی ایف ٹی',
      'shortName': 'Raast QR',
      'icon': Icons.qr_code_scanner_rounded,
      'color': 0xFF006622,
      'requiresPhone': false,
      'details': 'Raast ID: 0300-1234567\nBank: Meezan Bank Ltd\nTitle: Skill Bridge Escrow PK\nIBAN: PK29MEZN00012345678901',
    },
    {
      'id': 'card',
      'name': 'Debit / Credit Card',
      'shortName': 'Card',
      'icon': Icons.credit_card,
      'color': 0xFF4A154B,
      'requiresPhone': false,
    },
    {
      'id': 'cod',
      'name': 'Cash on Completion',
      'shortName': 'Cash',
      'icon': Icons.payments,
      'color': 0xFF2E7D32,
      'requiresPhone': false,
    },
  ];

  // ── Realistic Pakistani Worker Profiles (Seed / Fallback Data) ──────────
  static const List<Map<String, dynamic>> featuredWorkers = [
    {
      'id': 'worker_pk_1',
      'name': 'Muhammad Usman',
      'category': 'Solar Installer',
      'urdu': 'سولر انسٹالر',
      'rating': 4.9,
      'reviewsCount': 124,
      'hourlyRate': 2500,
      'city': 'Lahore',
      'address': 'DHA Phase 5, Lahore',
      'phone': '+92 300 4567891',
      'isVerified': true,
      'experienceYears': 7,
      'bio': 'Certified Solar & Inverter installation expert. Specializing in Nitrox, Growatt, and Huawei hybrid solar systems across Lahore.',
      'imageUrl': 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400',
    },
    {
      'id': 'worker_pk_2',
      'name': 'Tariq Mehmood',
      'category': 'AC Technician',
      'urdu': 'اے سی ٹیکنیشن',
      'rating': 4.8,
      'reviewsCount': 98,
      'hourlyRate': 1500,
      'city': 'Islamabad',
      'address': 'F-10 Markaz, Islamabad',
      'phone': '+92 333 5678901',
      'isVerified': true,
      'experienceYears': 9,
      'bio': 'Inverter AC repair, gas charging, and installation expert. Serving Islamabad and Rawalpindi with 100% satisfaction guarantee.',
      'imageUrl': 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400',
    },
    {
      'id': 'worker_pk_3',
      'name': 'Bilal Ahmed',
      'category': 'Electrician',
      'urdu': 'بجلی والا',
      'rating': 5.0,
      'reviewsCount': 156,
      'hourlyRate': 800,
      'city': 'Karachi',
      'address': 'Gulshan-e-Iqbal Block 13, Karachi',
      'phone': '+92 321 2345678',
      'isVerified': true,
      'experienceYears': 11,
      'bio': 'Licensed electrician for residential and commercial wiring, UPS installation, and fault debugging. Quick 30-min response in Karachi.',
      'imageUrl': 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=400',
    },
    {
      'id': 'worker_pk_4',
      'name': 'Imran Khan',
      'category': 'Plumber',
      'urdu': 'نلکے والا',
      'rating': 4.7,
      'reviewsCount': 82,
      'hourlyRate': 700,
      'city': 'Rawalpindi',
      'address': 'Satellite Town, Rawalpindi',
      'phone': '+92 345 3456789',
      'isVerified': true,
      'experienceYears': 6,
      'bio': 'Expert plumber for PPRC pipe fitting, water pump repair, geyser installation, and bathroom remodeling.',
      'imageUrl': 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400',
    },
    {
      'id': 'worker_pk_5',
      'name': 'Hamza Shah',
      'category': 'UPS & Generator',
      'urdu': 'یو پی ایس اور جنریٹر',
      'rating': 4.9,
      'reviewsCount': 110,
      'hourlyRate': 1200,
      'city': 'Lahore',
      'address': 'Johar Town, Lahore',
      'phone': '+92 301 8765432',
      'isVerified': true,
      'experienceYears': 8,
      'bio': 'Specialist in Homage, Inverex, and Honda silent generator tuning, battery maintenance, and automatic changeover wiring.',
      'imageUrl': 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400',
    },
    {
      'id': 'worker_pk_6',
      'name': 'Ayesha Noor',
      'category': 'Home Tutor',
      'urdu': 'ٹیوٹر',
      'rating': 5.0,
      'reviewsCount': 64,
      'hourlyRate': 1500,
      'city': 'Islamabad',
      'address': 'G-11/3, Islamabad',
      'phone': '+92 336 1122334',
      'isVerified': true,
      'experienceYears': 5,
      'bio': 'M.Phil Mathematics & Physics tutor for O-Level, A-Level, and FSc students. Interactive teaching method with proven exam results.',
      'imageUrl': 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400',
    },
  ];
}
